spring:
  application:
    name: BizSol Communication Agent

duckdb:
  file-path: ./data/comm-agent.db

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: metrics

logging.level.io.camunda.client.impl.CamundaCallCredentials: ERROR

