# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/
# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/configuration/

camunda:
  client:
    mode: saas
    auth:
      client-id: ...
      client-secret: ...
    cloud:
      cluster-id: ...
      region: ...

external:
  api:
    base-url: http://wiremock:8080